### ISSUE TITLE
질문에 대한 답변 삭제 - 1순위

### ISSUE THREAD

**Issue by CHEYOUNG-LIM** [021Skyfall/SideProject_QnA#11]
회원(고객)이 등록한 1건의 질문에 관리자가 등록한 답변을 삭제하는 기능
- 답변은 관리자만 삭제할 수 있다.
- 답변 삭제 시, 테이블에서 row 가 완전히 삭제되도록 한다.(기능 난이도를 고려한 요구사항)

**Comment by 021Skyfall** [comment]
처음에 삭제가 먹통이어서 이건 또 무슨 문제인가 했는데
에러 로그가 안떠서 찾기 굉장히 힘들었다

정답은 JPA에서 양방향 연관관계 매핑 시 객체간 관계를 끊어주어야 삭제할 수 있었던 것

즉, 삭제하고자하는 reply와 연결된 board 객체를 끊어주어야 삭제가 가능하다

삭제 방법은 연결된 board 객체를 가져온 다음 해당 객체 안의 reply 객체를 null로 바꾸어주면 된다


이렇게 해결했다


참고로 board 삭제 시에는 cascade 애트리뷰트를 사용해서 자동으로 지워진다.
연결된 하위 객체를 지워주는 orphanRemoval = true를 사용해도 가능하다

이 부분에서 그럼 반대는 어떻게 되지? 하고 힌트를 얻었다

-완-
